version: "3.3"

services:
  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: erolj/yopassid
    restart: always
    ports:
      - "17440:80"
    command: "--memcached=memcached:11211 --port 80"
